# Site settings
title: DBA Progress
description: 'You only have so many keystrokes in life, so use them well.' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/dbaprogress" # the subpath of your site, e.g. /blog
url: "https://cbrianpace.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/DBAProgress-logo-title.svg"
logo-icon: "/assets/img/branding/DBAProgress-logo-full.svg"
logo-icon-SEO: "/assets/img/branding/DBAProgress-logo-full.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/DBAProgress-logo-title.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Brian Pace # add your name
author-pic: Avatar_BrianPsm.jpg
about-author: Running databases at scale in the enterprise for 30+ years.

# Contact links
email: brian@dbaprogress.com # Add your Email address
phone: # Add your Phone number
website: https://cbrianpace.github.io # Add your website
linkedin: cbrianpace # Add your Linkedin handle
github: cbrianpace # Add your Github handle
twitter: '@brianofpace' # Add your Twitter handle
bandcamp:  # Add your Bandcamp username
stackoverflow:  # Add your stackoverflow account

# Newsletter
mailchimp: #

# Tracker
analytics: G-1S1EXX1LJN
#fbadmin: ar.maybach

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

extensions:
  mermaid_enable: true

# Comments
comments: utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: # The GitHub repo URL.  https://utteranc.es/
  issue_term: # The GitHub issue label
  label: # The GitHub comments label
  theme: # The GitHub comment's there. e.g. github-dark
  # Disqus
  discus_identifier: # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]